# Tabuleiro (base)
tabuleiro.linhas=6
tabuleiro.colunas=6
tabuleiro.tipos_peca=6

# Regras
regras.tamanho_minimo_match=3
regras.somente_troca_adjacente=true
regras.consumir_movimento_troca_invalida=false

# Pontuacao
pontuacao.match_3=500
pontuacao.match_4=1000
pontuacao.match_5_ou_mais=1500
pontuacao.multiplicador_cascata=1
pontuacao.pontuar_cascata=true

# Jogo
jogo.movimentos_iniciais=20
jogo.meta_pontos=5000

# Interface
ui.recurso_background=coffee_bg

# Audio (menu por padrao)
audio.habilitar_musica_fundo=true
audio.recurso_musica_fundo=luke_bergs_waesto_take_off
audio.volume_percentual=70
