package com.semstress;

import java.awt.Image;
import java.util.List;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JToggleButton;
import com.enums.NomeIconeEnum;

/**
 *
 * @author DiogoSouza
 */
public class TelaInicial extends javax.swing.JFrame {

    public TelaInicial() {

        initComponents();       
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("images/cup.png")); // load the image to a imageIcon                
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(80, 80,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        jLabelLogoJogo.setIcon(imageIcon);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabelPontosTitulo = new javax.swing.JLabel();
        jLabelPontosValor = new javax.swing.JLabel();
        jLabelMetaTitulo = new javax.swing.JLabel();
        jLabelMetaValor = new javax.swing.JLabel();
        jLabelMovimentosTitulo = new javax.swing.JLabel();
        jLabelMovimentosValor = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jLabelNomeJogo = new javax.swing.JLabel();
        jLabelLogoJogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setText("Desenvolvido por: Diogo da Cunha Souza");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 154, 113));
        jPanel1.setToolTipText("");

        jPanel2.setBackground(new java.awt.Color(114, 54, 24));

        jToggleButton1.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton1.setText("jToggleButton1");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton2.setText("jToggleButton2");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton3.setText("jToggleButton3");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToggleButton4.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton4.setText("jToggleButton4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToggleButton5.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton5.setText("jToggleButton5");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToggleButton6.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton6.setText("jToggleButton6");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton7.setText("jToggleButton7");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToggleButton8.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jToggleButton8.setText("jToggleButton8");
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        jToggleButton9.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton9.setText("jToggleButton9");
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jToggleButton10.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton10.setText("jToggleButton10");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        jToggleButton11.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton11.setText("jToggleButton11");
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        jToggleButton12.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton12.setText("jToggleButton12");
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        jToggleButton13.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton13.setText("jToggleButton13");
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        jToggleButton14.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton14.setText("jToggleButton14");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        jToggleButton15.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton15.setText("jToggleButton15");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        jToggleButton16.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton16.setText("jToggleButton16");
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        jToggleButton17.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton17.setText("jToggleButton17");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });

        jToggleButton18.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton18.setText("jToggleButton18");
        jToggleButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton18ActionPerformed(evt);
            }
        });

        jToggleButton19.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton19.setText("jToggleButton19");
        jToggleButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton19ActionPerformed(evt);
            }
        });

        jToggleButton20.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton20.setText("jToggleButton20");
        jToggleButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton20ActionPerformed(evt);
            }
        });

        jToggleButton21.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton21.setText("jToggleButton21");
        jToggleButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton21ActionPerformed(evt);
            }
        });

        jToggleButton22.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton22.setText("jToggleButton22");
        jToggleButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton22ActionPerformed(evt);
            }
        });

        jToggleButton23.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton23.setText("jToggleButton23");
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });

        jToggleButton24.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton24.setText("jToggleButton24");
        jToggleButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton24ActionPerformed(evt);
            }
        });

        jToggleButton25.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton25.setText("jToggleButton25");
        jToggleButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton25ActionPerformed(evt);
            }
        });

        jToggleButton26.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton26.setText("jToggleButton26");
        jToggleButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton26ActionPerformed(evt);
            }
        });

        jToggleButton27.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton27.setText("jToggleButton27");
        jToggleButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton27ActionPerformed(evt);
            }
        });

        jToggleButton28.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton28.setText("jToggleButton28");
        jToggleButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton28ActionPerformed(evt);
            }
        });

        jToggleButton29.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton29.setText("jToggleButton29");
        jToggleButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton29ActionPerformed(evt);
            }
        });

        jToggleButton30.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton30.setText("jToggleButton30");
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });

        jToggleButton31.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton31.setText("jToggleButton31");
        jToggleButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton31ActionPerformed(evt);
            }
        });

        jToggleButton32.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton32.setText("jToggleButton32");
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });

        jToggleButton33.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton33.setText("jToggleButton33");
        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });

        jToggleButton34.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton34.setText("jToggleButton34");
        jToggleButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton34ActionPerformed(evt);
            }
        });

        jToggleButton35.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton35.setText("jToggleButton35");
        jToggleButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton35ActionPerformed(evt);
            }
        });

        jToggleButton36.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton36.setText("jToggleButton36");
        jToggleButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton36ActionPerformed(evt);
            }
        });

        jToggleButton37.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton37.setText("jToggleButton37");
        jToggleButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton37ActionPerformed(evt);
            }
        });

        jToggleButton38.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton38.setText("jToggleButton38");
        jToggleButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton38ActionPerformed(evt);
            }
        });

        jToggleButton39.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton39.setText("jToggleButton39");
        jToggleButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton39ActionPerformed(evt);
            }
        });

        jToggleButton40.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton40.setText("jToggleButton40");
        jToggleButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton40ActionPerformed(evt);
            }
        });

        jToggleButton41.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton41.setText("jToggleButton41");
        jToggleButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton41ActionPerformed(evt);
            }
        });

        jToggleButton42.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton42.setText("jToggleButton42");
        jToggleButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton42ActionPerformed(evt);
            }
        });

        jToggleButton43.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton43.setText("jToggleButton43");
        jToggleButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton43ActionPerformed(evt);
            }
        });

        jToggleButton44.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton44.setText("jToggleButton44");
        jToggleButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton44ActionPerformed(evt);
            }
        });

        jToggleButton45.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton45.setText("jToggleButton45");
        jToggleButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton45ActionPerformed(evt);
            }
        });

        jToggleButton46.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton46.setText("jToggleButton46");
        jToggleButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton46ActionPerformed(evt);
            }
        });

        jToggleButton47.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton47.setText("jToggleButton47");
        jToggleButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton47ActionPerformed(evt);
            }
        });

        jToggleButton48.setBackground(new java.awt.Color(114, 54, 24));
        jToggleButton48.setText("jToggleButton48");
        jToggleButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton48ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jToggleButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToggleButton15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToggleButton23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jToggleButton17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jToggleButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jToggleButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jToggleButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton9)
                    .addComponent(jToggleButton17)
                    .addComponent(jToggleButton25)
                    .addComponent(jToggleButton33)
                    .addComponent(jToggleButton41))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton2)
                    .addComponent(jToggleButton10)
                    .addComponent(jToggleButton18)
                    .addComponent(jToggleButton26)
                    .addComponent(jToggleButton34)
                    .addComponent(jToggleButton42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton3)
                    .addComponent(jToggleButton11)
                    .addComponent(jToggleButton19)
                    .addComponent(jToggleButton27)
                    .addComponent(jToggleButton35)
                    .addComponent(jToggleButton43))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton4)
                    .addComponent(jToggleButton12)
                    .addComponent(jToggleButton20)
                    .addComponent(jToggleButton28)
                    .addComponent(jToggleButton36)
                    .addComponent(jToggleButton44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton5)
                    .addComponent(jToggleButton13)
                    .addComponent(jToggleButton21)
                    .addComponent(jToggleButton29)
                    .addComponent(jToggleButton37)
                    .addComponent(jToggleButton45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton14)
                    .addComponent(jToggleButton22)
                    .addComponent(jToggleButton30)
                    .addComponent(jToggleButton38)
                    .addComponent(jToggleButton46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton7)
                    .addComponent(jToggleButton15)
                    .addComponent(jToggleButton23)
                    .addComponent(jToggleButton31)
                    .addComponent(jToggleButton39)
                    .addComponent(jToggleButton47))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton8)
                    .addComponent(jToggleButton16)
                    .addComponent(jToggleButton24)
                    .addComponent(jToggleButton32)
                    .addComponent(jToggleButton40)
                    .addComponent(jToggleButton48))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabelPontosTitulo.setText("Pontos");

        jLabelPontosValor.setText("0");

        jLabelMetaTitulo.setText("Meta");

        jLabelMetaValor.setText("XXXX");

        jLabelMovimentosTitulo.setText("Movimentos");

        jLabelMovimentosValor.setText("XXXX");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPontosTitulo)
                            .addComponent(jLabelMetaTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMetaValor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPontosValor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabelMovimentosValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jLabelMovimentosTitulo)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelPontosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPontosValor)
                .addGap(53, 53, 53)
                .addComponent(jLabelMetaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMetaValor)
                .addGap(56, 56, 56)
                .addComponent(jLabelMovimentosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMovimentosValor)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabelNomeJogo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelNomeJogo.setText("Coffe Crush");

        jLabelLogoJogo.setText("*");

        jLabel1.setText("Develop By Diogo Souza");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelLogoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jLabelNomeJogo))))))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogoJogo)
                    .addComponent(jLabelNomeJogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciar)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarImagens(){
        atualizarCampoSelecionado(jToggleButton1);
        atualizarCampoSelecionado(jToggleButton2);
        atualizarCampoSelecionado(jToggleButton3);
        atualizarCampoSelecionado(jToggleButton4);
        atualizarCampoSelecionado(jToggleButton5);
        atualizarCampoSelecionado(jToggleButton6);
        atualizarCampoSelecionado(jToggleButton7);
        atualizarCampoSelecionado(jToggleButton8);
        atualizarCampoSelecionado(jToggleButton9);
        atualizarCampoSelecionado(jToggleButton10);
        atualizarCampoSelecionado(jToggleButton11);
        atualizarCampoSelecionado(jToggleButton12);
        atualizarCampoSelecionado(jToggleButton13);
        atualizarCampoSelecionado(jToggleButton14);
        atualizarCampoSelecionado(jToggleButton15);
        atualizarCampoSelecionado(jToggleButton16);
        atualizarCampoSelecionado(jToggleButton17);
        atualizarCampoSelecionado(jToggleButton18);
        atualizarCampoSelecionado(jToggleButton19);
        atualizarCampoSelecionado(jToggleButton20);
        atualizarCampoSelecionado(jToggleButton21);
        atualizarCampoSelecionado(jToggleButton22);
        atualizarCampoSelecionado(jToggleButton23);
        atualizarCampoSelecionado(jToggleButton24);
        atualizarCampoSelecionado(jToggleButton25);
        atualizarCampoSelecionado(jToggleButton26);
        atualizarCampoSelecionado(jToggleButton27);
        atualizarCampoSelecionado(jToggleButton28);
        atualizarCampoSelecionado(jToggleButton29);
        atualizarCampoSelecionado(jToggleButton30);
        atualizarCampoSelecionado(jToggleButton31);
        atualizarCampoSelecionado(jToggleButton32);
        atualizarCampoSelecionado(jToggleButton33);
        atualizarCampoSelecionado(jToggleButton34);
        atualizarCampoSelecionado(jToggleButton35);
        atualizarCampoSelecionado(jToggleButton36);
        atualizarCampoSelecionado(jToggleButton37);
        atualizarCampoSelecionado(jToggleButton38);
        atualizarCampoSelecionado(jToggleButton39);
        atualizarCampoSelecionado(jToggleButton40);
        atualizarCampoSelecionado(jToggleButton41);
        atualizarCampoSelecionado(jToggleButton42);
        atualizarCampoSelecionado(jToggleButton43);
        atualizarCampoSelecionado(jToggleButton44);
        atualizarCampoSelecionado(jToggleButton45);
        atualizarCampoSelecionado(jToggleButton46);
        atualizarCampoSelecionado(jToggleButton47);
        atualizarCampoSelecionado(jToggleButton48);
        
    }
    
    private void reduzirMovimento(){
        int movimentos = Integer.parseInt(jLabelMovimentosValor.getText());
        movimentos--;
        
        jLabelMovimentosValor.setText(String.valueOf(movimentos));
        
    }
    
    private void verificaMovimentosRestantes(){
        int movimentos = Integer.parseInt(jLabelMovimentosValor.getText());
        if(movimentos<=0){
            
            this.setVisible(false);
            
            GameOver gameOver = new GameOver();
            gameOver.pontuacaoFinal(jLabelPontosValor.getText());
            gameOver.setVisible(true);

        }
    }
            
    public void atualizarCampoSelecionado(JToggleButton jToggleButton){
        
        switch (jToggleButton.getText()) {
            case "0":
                jToggleButton.setIcon(iconesJogo.retornarIcone(NomeIconeEnum.COFFEE_BEANS));
                break;
            case "1":
                jToggleButton.setIcon(iconesJogo.retornarIcone(NomeIconeEnum.COFFEE_BROWN));
                break;
            case "2":
                jToggleButton.setIcon(iconesJogo.retornarIcone(NomeIconeEnum.COFFEE_WHITE));
                break;
            case "3":
                jToggleButton.setIcon(iconesJogo.retornarIcone(NomeIconeEnum.COFFEE_YELLOW));
                break;
            case "4":
                jToggleButton.setIcon(iconesJogo.retornarIcone(NomeIconeEnum.COFFEE_RED));
                break;
            default:
                break;
        }

    }
    
    public void verificarSeBotaoEstaPrecionado(JToggleButton jToggleButtonPai, JToggleButton jToggleButtonFilho){
        if(jToggleButtonFilho.isSelected()){
            String texto = jToggleButtonFilho.getText();
            Icon icone = jToggleButtonFilho.getIcon();
            
            jToggleButtonFilho.setText(jToggleButtonPai.getText());
            jToggleButtonFilho.setIcon(jToggleButtonPai.getIcon());
            
            jToggleButtonPai.setText(texto);
            jToggleButtonPai.setIcon(icone);
            
            jToggleButtonPai.setSelected(false);
            jToggleButtonFilho.setSelected(false);
            
            reduzirMovimento();
            verificaMovimentosRestantes();
            
            //verifica e faz o match
            int pontosGanhos=0; 
            pontosGanhos += verificarMatchTodaTabela();
            int pontosAtuais = Integer.parseInt(jLabelPontosValor.getText());
            pontosAtuais+=pontosGanhos;
            jLabelPontosValor.setText(String.valueOf(pontosAtuais));
            
        }
    }
    
    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        jToggleButton1.setText(funcionalidades.gerarValorRandomico());
        jToggleButton2.setText(funcionalidades.gerarValorRandomico());
        jToggleButton3.setText(funcionalidades.gerarValorRandomico());
        jToggleButton4.setText(funcionalidades.gerarValorRandomico());
        jToggleButton5.setText(funcionalidades.gerarValorRandomico());
        jToggleButton6.setText(funcionalidades.gerarValorRandomico());
        jToggleButton7.setText(funcionalidades.gerarValorRandomico());
        jToggleButton8.setText(funcionalidades.gerarValorRandomico());
        jToggleButton9.setText(funcionalidades.gerarValorRandomico());
        jToggleButton10.setText(funcionalidades.gerarValorRandomico());
        jToggleButton11.setText(funcionalidades.gerarValorRandomico());
        jToggleButton12.setText(funcionalidades.gerarValorRandomico());
        jToggleButton13.setText(funcionalidades.gerarValorRandomico());
        jToggleButton14.setText(funcionalidades.gerarValorRandomico());
        jToggleButton15.setText(funcionalidades.gerarValorRandomico());
        jToggleButton16.setText(funcionalidades.gerarValorRandomico());
        jToggleButton17.setText(funcionalidades.gerarValorRandomico());
        jToggleButton18.setText(funcionalidades.gerarValorRandomico());
        jToggleButton19.setText(funcionalidades.gerarValorRandomico());
        jToggleButton20.setText(funcionalidades.gerarValorRandomico());
        jToggleButton21.setText(funcionalidades.gerarValorRandomico());
        jToggleButton22.setText(funcionalidades.gerarValorRandomico());
        jToggleButton23.setText(funcionalidades.gerarValorRandomico());
        jToggleButton24.setText(funcionalidades.gerarValorRandomico());
        jToggleButton25.setText(funcionalidades.gerarValorRandomico());
        jToggleButton26.setText(funcionalidades.gerarValorRandomico());
        jToggleButton27.setText(funcionalidades.gerarValorRandomico());
        jToggleButton28.setText(funcionalidades.gerarValorRandomico());
        jToggleButton29.setText(funcionalidades.gerarValorRandomico());
        jToggleButton30.setText(funcionalidades.gerarValorRandomico());
        jToggleButton31.setText(funcionalidades.gerarValorRandomico());
        jToggleButton32.setText(funcionalidades.gerarValorRandomico());
        jToggleButton33.setText(funcionalidades.gerarValorRandomico());
        jToggleButton34.setText(funcionalidades.gerarValorRandomico());
        jToggleButton35.setText(funcionalidades.gerarValorRandomico());
        jToggleButton36.setText(funcionalidades.gerarValorRandomico());
        jToggleButton37.setText(funcionalidades.gerarValorRandomico());
        jToggleButton38.setText(funcionalidades.gerarValorRandomico());
        jToggleButton39.setText(funcionalidades.gerarValorRandomico());
        jToggleButton40.setText(funcionalidades.gerarValorRandomico());
        jToggleButton41.setText(funcionalidades.gerarValorRandomico());
        jToggleButton42.setText(funcionalidades.gerarValorRandomico());
        jToggleButton43.setText(funcionalidades.gerarValorRandomico());
        jToggleButton44.setText(funcionalidades.gerarValorRandomico());
        jToggleButton45.setText(funcionalidades.gerarValorRandomico());
        jToggleButton46.setText(funcionalidades.gerarValorRandomico());
        jToggleButton47.setText(funcionalidades.gerarValorRandomico());
        jToggleButton48.setText(funcionalidades.gerarValorRandomico());
        
        atualizarImagens();
        
        jLabelMovimentosValor.setText("30");
        jButtonIniciar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    public int verificarMatchTodaTabela(){
        
        int pontos=0;
        
        List<JToggleButton> jToggleButtonsColuna1 = new ArrayList<>();
        jToggleButtonsColuna1.add(jToggleButton1);
        jToggleButtonsColuna1.add(jToggleButton2);
        jToggleButtonsColuna1.add(jToggleButton3);
        jToggleButtonsColuna1.add(jToggleButton4);
        jToggleButtonsColuna1.add(jToggleButton5);
        jToggleButtonsColuna1.add(jToggleButton6);
        jToggleButtonsColuna1.add(jToggleButton7);
        jToggleButtonsColuna1.add(jToggleButton8);
        
        //Depois com o retorno do metodo abaixo somar na pontuacao
        pontos += funcionalidades.verificarMatchVerticalColuna(jToggleButtonsColuna1);

        List<JToggleButton> jToggleButtonsColuna2 = new ArrayList<>();
        jToggleButtonsColuna2.add(jToggleButton9);
        jToggleButtonsColuna2.add(jToggleButton10);
        jToggleButtonsColuna2.add(jToggleButton11);
        jToggleButtonsColuna2.add(jToggleButton12);
        jToggleButtonsColuna2.add(jToggleButton13);
        jToggleButtonsColuna2.add(jToggleButton14);
        jToggleButtonsColuna2.add(jToggleButton15);
        jToggleButtonsColuna2.add(jToggleButton16);
        
        //Depois com o retorno do metodo abaixo somar na pontuacao
        pontos += funcionalidades.verificarMatchVerticalColuna(jToggleButtonsColuna2);
        
        List<JToggleButton> jToggleButtonsColuna3 = new ArrayList<>();
        jToggleButtonsColuna3.add(jToggleButton17);
        jToggleButtonsColuna3.add(jToggleButton18);
        jToggleButtonsColuna3.add(jToggleButton19);
        jToggleButtonsColuna3.add(jToggleButton20);
        jToggleButtonsColuna3.add(jToggleButton21);
        jToggleButtonsColuna3.add(jToggleButton22);
        jToggleButtonsColuna3.add(jToggleButton23);
        jToggleButtonsColuna3.add(jToggleButton24);
        
        //Depois com o retorno do metodo abaixo somar na pontuacao
        pontos += funcionalidades.verificarMatchVerticalColuna(jToggleButtonsColuna3);
        
        List<JToggleButton> jToggleButtonsColuna4 = new ArrayList<>();
        jToggleButtonsColuna4.add(jToggleButton25);
        jToggleButtonsColuna4.add(jToggleButton26);
        jToggleButtonsColuna4.add(jToggleButton27);
        jToggleButtonsColuna4.add(jToggleButton28);
        jToggleButtonsColuna4.add(jToggleButton29);
        jToggleButtonsColuna4.add(jToggleButton30);
        jToggleButtonsColuna4.add(jToggleButton31);
        jToggleButtonsColuna4.add(jToggleButton32);
        
        //Depois com o retorno do metodo abaixo somar na pontuacao
        pontos += funcionalidades.verificarMatchVerticalColuna(jToggleButtonsColuna4);
        
        List<JToggleButton> jToggleButtonsColuna5 = new ArrayList<>();
        jToggleButtonsColuna5.add(jToggleButton33);
        jToggleButtonsColuna5.add(jToggleButton34);
        jToggleButtonsColuna5.add(jToggleButton35);
        jToggleButtonsColuna5.add(jToggleButton36);
        jToggleButtonsColuna5.add(jToggleButton37);
        jToggleButtonsColuna5.add(jToggleButton38);
        jToggleButtonsColuna5.add(jToggleButton39);
        jToggleButtonsColuna5.add(jToggleButton40);
        
        //Depois com o retorno do metodo abaixo somar na pontuacao
        pontos += funcionalidades.verificarMatchVerticalColuna(jToggleButtonsColuna5);
        
        List<JToggleButton> jToggleButtonsColuna6 = new ArrayList<>();
        jToggleButtonsColuna6.add(jToggleButton41);
        jToggleButtonsColuna6.add(jToggleButton42);
        jToggleButtonsColuna6.add(jToggleButton43);
        jToggleButtonsColuna6.add(jToggleButton44);
        jToggleButtonsColuna6.add(jToggleButton45);
        jToggleButtonsColuna6.add(jToggleButton46);
        jToggleButtonsColuna6.add(jToggleButton47);
        jToggleButtonsColuna6.add(jToggleButton48);
        
        //Depois com o retorno do metodo abaixo somar na pontuacao
        pontos += funcionalidades.verificarMatchVerticalColuna(jToggleButtonsColuna6);
        
        return pontos;
    }
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton1, jToggleButton9);
        verificarSeBotaoEstaPrecionado(jToggleButton1, jToggleButton2);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton2, jToggleButton1);
        verificarSeBotaoEstaPrecionado(jToggleButton2, jToggleButton10);
        verificarSeBotaoEstaPrecionado(jToggleButton2, jToggleButton3);
        
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton3, jToggleButton2);
        verificarSeBotaoEstaPrecionado(jToggleButton3, jToggleButton11);
        verificarSeBotaoEstaPrecionado(jToggleButton3, jToggleButton4);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton4, jToggleButton3);
        verificarSeBotaoEstaPrecionado(jToggleButton4, jToggleButton12);
        verificarSeBotaoEstaPrecionado(jToggleButton4, jToggleButton5);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton5, jToggleButton4);
        verificarSeBotaoEstaPrecionado(jToggleButton5, jToggleButton13);
        verificarSeBotaoEstaPrecionado(jToggleButton5, jToggleButton6);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton6, jToggleButton5);
        verificarSeBotaoEstaPrecionado(jToggleButton6, jToggleButton14);
        verificarSeBotaoEstaPrecionado(jToggleButton6, jToggleButton7);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton7, jToggleButton6);
        verificarSeBotaoEstaPrecionado(jToggleButton7, jToggleButton15);
        verificarSeBotaoEstaPrecionado(jToggleButton7, jToggleButton8);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton8, jToggleButton7);
        verificarSeBotaoEstaPrecionado(jToggleButton8, jToggleButton16);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton9, jToggleButton1);
        verificarSeBotaoEstaPrecionado(jToggleButton9, jToggleButton10);
        verificarSeBotaoEstaPrecionado(jToggleButton9, jToggleButton17);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton10, jToggleButton9);
        verificarSeBotaoEstaPrecionado(jToggleButton10, jToggleButton2);
        verificarSeBotaoEstaPrecionado(jToggleButton10, jToggleButton11);
        verificarSeBotaoEstaPrecionado(jToggleButton10, jToggleButton18);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton11, jToggleButton10);
        verificarSeBotaoEstaPrecionado(jToggleButton11, jToggleButton3);
        verificarSeBotaoEstaPrecionado(jToggleButton11, jToggleButton12);
        verificarSeBotaoEstaPrecionado(jToggleButton11, jToggleButton19);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton12, jToggleButton11);
        verificarSeBotaoEstaPrecionado(jToggleButton12, jToggleButton4);
        verificarSeBotaoEstaPrecionado(jToggleButton12, jToggleButton13);
        verificarSeBotaoEstaPrecionado(jToggleButton12, jToggleButton20);
    }//GEN-LAST:event_jToggleButton12ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton13, jToggleButton12);
        verificarSeBotaoEstaPrecionado(jToggleButton13, jToggleButton5);
        verificarSeBotaoEstaPrecionado(jToggleButton13, jToggleButton14);
        verificarSeBotaoEstaPrecionado(jToggleButton13, jToggleButton21);
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton14, jToggleButton13);
        verificarSeBotaoEstaPrecionado(jToggleButton14, jToggleButton6);
        verificarSeBotaoEstaPrecionado(jToggleButton14, jToggleButton15);
        verificarSeBotaoEstaPrecionado(jToggleButton14, jToggleButton22);
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton15, jToggleButton14);
        verificarSeBotaoEstaPrecionado(jToggleButton15, jToggleButton7);
        verificarSeBotaoEstaPrecionado(jToggleButton15, jToggleButton16);
        verificarSeBotaoEstaPrecionado(jToggleButton15, jToggleButton23);
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton16, jToggleButton15);
        verificarSeBotaoEstaPrecionado(jToggleButton16, jToggleButton8);
        verificarSeBotaoEstaPrecionado(jToggleButton16, jToggleButton24);
    }//GEN-LAST:event_jToggleButton16ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton17, jToggleButton9);
        verificarSeBotaoEstaPrecionado(jToggleButton17, jToggleButton18);
        verificarSeBotaoEstaPrecionado(jToggleButton17, jToggleButton25);
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton18ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton18, jToggleButton17);
        verificarSeBotaoEstaPrecionado(jToggleButton18, jToggleButton10);
        verificarSeBotaoEstaPrecionado(jToggleButton18, jToggleButton19);
        verificarSeBotaoEstaPrecionado(jToggleButton18, jToggleButton26);
    }//GEN-LAST:event_jToggleButton18ActionPerformed

    private void jToggleButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton19ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton19, jToggleButton18);
        verificarSeBotaoEstaPrecionado(jToggleButton19, jToggleButton11);
        verificarSeBotaoEstaPrecionado(jToggleButton19, jToggleButton20);
        verificarSeBotaoEstaPrecionado(jToggleButton19, jToggleButton27);
    }//GEN-LAST:event_jToggleButton19ActionPerformed

    private void jToggleButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton20ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton20, jToggleButton19);
        verificarSeBotaoEstaPrecionado(jToggleButton20, jToggleButton12);
        verificarSeBotaoEstaPrecionado(jToggleButton20, jToggleButton21);
        verificarSeBotaoEstaPrecionado(jToggleButton20, jToggleButton28);
    }//GEN-LAST:event_jToggleButton20ActionPerformed

    private void jToggleButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton21ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton21, jToggleButton20);
        verificarSeBotaoEstaPrecionado(jToggleButton21, jToggleButton13);
        verificarSeBotaoEstaPrecionado(jToggleButton21, jToggleButton22);
        verificarSeBotaoEstaPrecionado(jToggleButton21, jToggleButton29);
    }//GEN-LAST:event_jToggleButton21ActionPerformed

    private void jToggleButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton22ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton22, jToggleButton21);
        verificarSeBotaoEstaPrecionado(jToggleButton22, jToggleButton14);
        verificarSeBotaoEstaPrecionado(jToggleButton22, jToggleButton23);
        verificarSeBotaoEstaPrecionado(jToggleButton22, jToggleButton30);
    }//GEN-LAST:event_jToggleButton22ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton23, jToggleButton22);
        verificarSeBotaoEstaPrecionado(jToggleButton23, jToggleButton15);
        verificarSeBotaoEstaPrecionado(jToggleButton23, jToggleButton24);
        verificarSeBotaoEstaPrecionado(jToggleButton23, jToggleButton31);
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton24ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton24, jToggleButton23);
        verificarSeBotaoEstaPrecionado(jToggleButton24, jToggleButton16);
        verificarSeBotaoEstaPrecionado(jToggleButton24, jToggleButton32);
    }//GEN-LAST:event_jToggleButton24ActionPerformed

    private void jToggleButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton25ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton25, jToggleButton17);
        verificarSeBotaoEstaPrecionado(jToggleButton25, jToggleButton26);
        verificarSeBotaoEstaPrecionado(jToggleButton25, jToggleButton33);
    }//GEN-LAST:event_jToggleButton25ActionPerformed

    private void jToggleButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton26ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton26, jToggleButton25);
        verificarSeBotaoEstaPrecionado(jToggleButton26, jToggleButton18);
        verificarSeBotaoEstaPrecionado(jToggleButton26, jToggleButton27);
        verificarSeBotaoEstaPrecionado(jToggleButton26, jToggleButton34);
    }//GEN-LAST:event_jToggleButton26ActionPerformed

    private void jToggleButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton27ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton27, jToggleButton26);
        verificarSeBotaoEstaPrecionado(jToggleButton27, jToggleButton19);
        verificarSeBotaoEstaPrecionado(jToggleButton27, jToggleButton28);
        verificarSeBotaoEstaPrecionado(jToggleButton27, jToggleButton35);
    }//GEN-LAST:event_jToggleButton27ActionPerformed

    private void jToggleButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton28ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton28, jToggleButton27);
        verificarSeBotaoEstaPrecionado(jToggleButton28, jToggleButton20);
        verificarSeBotaoEstaPrecionado(jToggleButton28, jToggleButton29);
        verificarSeBotaoEstaPrecionado(jToggleButton28, jToggleButton36);
    }//GEN-LAST:event_jToggleButton28ActionPerformed

    private void jToggleButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton29ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton29, jToggleButton28);
        verificarSeBotaoEstaPrecionado(jToggleButton29, jToggleButton21);
        verificarSeBotaoEstaPrecionado(jToggleButton29, jToggleButton30);
        verificarSeBotaoEstaPrecionado(jToggleButton29, jToggleButton37);
    }//GEN-LAST:event_jToggleButton29ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton30, jToggleButton29);
        verificarSeBotaoEstaPrecionado(jToggleButton30, jToggleButton31);
        verificarSeBotaoEstaPrecionado(jToggleButton30, jToggleButton22);
        verificarSeBotaoEstaPrecionado(jToggleButton30, jToggleButton38);
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton31ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton31, jToggleButton30);
        verificarSeBotaoEstaPrecionado(jToggleButton31, jToggleButton32);
        verificarSeBotaoEstaPrecionado(jToggleButton31, jToggleButton23);
        verificarSeBotaoEstaPrecionado(jToggleButton31, jToggleButton39);
    }//GEN-LAST:event_jToggleButton31ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton32, jToggleButton31);
        verificarSeBotaoEstaPrecionado(jToggleButton32, jToggleButton24);
        verificarSeBotaoEstaPrecionado(jToggleButton32, jToggleButton40);
    }//GEN-LAST:event_jToggleButton32ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton33, jToggleButton25);
        verificarSeBotaoEstaPrecionado(jToggleButton33, jToggleButton34);
        verificarSeBotaoEstaPrecionado(jToggleButton33, jToggleButton41);
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton34ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton34, jToggleButton33);
        verificarSeBotaoEstaPrecionado(jToggleButton34, jToggleButton26);
        verificarSeBotaoEstaPrecionado(jToggleButton34, jToggleButton35);
        verificarSeBotaoEstaPrecionado(jToggleButton34, jToggleButton42);
    }//GEN-LAST:event_jToggleButton34ActionPerformed

    private void jToggleButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton35ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton35, jToggleButton34);
        verificarSeBotaoEstaPrecionado(jToggleButton35, jToggleButton36);
        verificarSeBotaoEstaPrecionado(jToggleButton35, jToggleButton27);
        verificarSeBotaoEstaPrecionado(jToggleButton35, jToggleButton43);
    }//GEN-LAST:event_jToggleButton35ActionPerformed

    private void jToggleButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton36ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton36, jToggleButton35);
        verificarSeBotaoEstaPrecionado(jToggleButton36, jToggleButton37);
        verificarSeBotaoEstaPrecionado(jToggleButton36, jToggleButton28);
        verificarSeBotaoEstaPrecionado(jToggleButton36, jToggleButton44);
    }//GEN-LAST:event_jToggleButton36ActionPerformed

    private void jToggleButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton37ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton37, jToggleButton36);
        verificarSeBotaoEstaPrecionado(jToggleButton37, jToggleButton38);
        verificarSeBotaoEstaPrecionado(jToggleButton37, jToggleButton29);
        verificarSeBotaoEstaPrecionado(jToggleButton37, jToggleButton45);
    }//GEN-LAST:event_jToggleButton37ActionPerformed

    private void jToggleButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton38ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton38, jToggleButton37);
        verificarSeBotaoEstaPrecionado(jToggleButton38, jToggleButton39);
        verificarSeBotaoEstaPrecionado(jToggleButton38, jToggleButton30);
        verificarSeBotaoEstaPrecionado(jToggleButton38, jToggleButton46);
    }//GEN-LAST:event_jToggleButton38ActionPerformed

    private void jToggleButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton39ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton39, jToggleButton38);
        verificarSeBotaoEstaPrecionado(jToggleButton39, jToggleButton40);
        verificarSeBotaoEstaPrecionado(jToggleButton39, jToggleButton31);
        verificarSeBotaoEstaPrecionado(jToggleButton39, jToggleButton47);
    }//GEN-LAST:event_jToggleButton39ActionPerformed

    private void jToggleButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton40ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton40, jToggleButton39);
        verificarSeBotaoEstaPrecionado(jToggleButton40, jToggleButton32);
        verificarSeBotaoEstaPrecionado(jToggleButton40, jToggleButton48);
    }//GEN-LAST:event_jToggleButton40ActionPerformed

    private void jToggleButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton41ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton41, jToggleButton33);
        verificarSeBotaoEstaPrecionado(jToggleButton41, jToggleButton42);
    }//GEN-LAST:event_jToggleButton41ActionPerformed

    private void jToggleButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton42ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton42, jToggleButton41);
        verificarSeBotaoEstaPrecionado(jToggleButton42, jToggleButton34);
        verificarSeBotaoEstaPrecionado(jToggleButton42, jToggleButton43);
    }//GEN-LAST:event_jToggleButton42ActionPerformed

    private void jToggleButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton43ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton43, jToggleButton42);
        verificarSeBotaoEstaPrecionado(jToggleButton43, jToggleButton44);
        verificarSeBotaoEstaPrecionado(jToggleButton43, jToggleButton35);
    }//GEN-LAST:event_jToggleButton43ActionPerformed

    private void jToggleButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton44ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton44, jToggleButton43);
        verificarSeBotaoEstaPrecionado(jToggleButton44, jToggleButton45);
        verificarSeBotaoEstaPrecionado(jToggleButton44, jToggleButton36);
    }//GEN-LAST:event_jToggleButton44ActionPerformed

    private void jToggleButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton45ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton40, jToggleButton44);
        verificarSeBotaoEstaPrecionado(jToggleButton40, jToggleButton46);
        verificarSeBotaoEstaPrecionado(jToggleButton40, jToggleButton37);
    }//GEN-LAST:event_jToggleButton45ActionPerformed

    private void jToggleButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton46ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton47, jToggleButton45);
        verificarSeBotaoEstaPrecionado(jToggleButton47, jToggleButton47);
        verificarSeBotaoEstaPrecionado(jToggleButton47, jToggleButton38);
    }//GEN-LAST:event_jToggleButton46ActionPerformed

    private void jToggleButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton47ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton47, jToggleButton46);
        verificarSeBotaoEstaPrecionado(jToggleButton47, jToggleButton48);
        verificarSeBotaoEstaPrecionado(jToggleButton47, jToggleButton39);
    }//GEN-LAST:event_jToggleButton47ActionPerformed

    private void jToggleButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton48ActionPerformed
        verificarSeBotaoEstaPrecionado(jToggleButton48, jToggleButton47);
        verificarSeBotaoEstaPrecionado(jToggleButton48, jToggleButton40);
    }//GEN-LAST:event_jToggleButton48ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLogoJogo;
    private javax.swing.JLabel jLabelMetaTitulo;
    private javax.swing.JLabel jLabelMetaValor;
    private javax.swing.JLabel jLabelMovimentosTitulo;
    private javax.swing.JLabel jLabelMovimentosValor;
    private javax.swing.JLabel jLabelNomeJogo;
    private javax.swing.JLabel jLabelPontosTitulo;
    private javax.swing.JLabel jLabelPontosValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
    private Funcionalidades funcionalidades = new Funcionalidades();
    private IconesJogo iconesJogo = new IconesJogo();
}
